config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
      collection do
          post :confirm
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only:[:show, :edit, :update, :destroy
  ]
  
  def index
    @blogs = Blog.all
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice:"つぶやきを投稿しました！"
    else
      render 'new'
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "つぶやきを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:content)
  end
  
  # idをキーとして値を取得するメソッドを追加
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/views/blogs/_form.html.erb
<div id="main">

<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="blog_title">
    <%= form.label :"つぶやき内容" %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit "つぶやく" %>
<% end %>

<p class="btn_back"><%= link_to "つぶやき一覧画面にもどる", blogs_path %></p>

</div>

app/views/blogs/confirm.html.erb
<div id="main">

<h3>以下の内容でつぶやきますか？</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    
    <p>つぶやき：<%= @blog.content %></p>
    <%= form.submit "つぶやきを登録する" %>
<% end %>

<!--app/views/blogs/confirm.html.erb に戻るボタン用のform_withを作成する-->
<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :content %>
    <%= form.submit "戻る", name: 'back' %>
<% end %>

</div>

app/views/blogs/edit.html.erb
<div id="main">

<h2>つぶやきを編集する</h2>

<%= render 'form' %>

</div>

app/views/blogs/index.html.erb
<div id="main">

<h1>あなたのつぶやき一覧</h1>

<p><%= notice %></p>

<table>
    
<% @blogs.each do |blog| %>
    <tr>
        <td><%= blog.content %></td>
        <td><%= link_to '詳細を確認', blog_path(blog.id) %></td>
        <td><%= link_to '編集', edit_blog_path(blog.id) %></td>
        <td><%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
<% end %>
</table>

<p class="btn_new"><%= link_to '新しくつぶやきを投稿する', new_blog_path %></p>

</div>

app/views/blogs/new.html.erb
<div id="main">

<h2>つぶやきを作成する</h2>

<%= render 'form' %>

</div>

app/views/blogs/show.html.erb
<div id="main">

<h1>つぶやき詳細画面</h1>
<p>内容：<%= @blog.content %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <!--<meta name="viewport" content="width=device-width">-->
    <!--assets/stylesheets以下にある全てのcssファイル、assets/javascript以下にあるJavaScriptファイルを読込-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <p class="logo"><a href="/blogs">TwitterClone</a></li></p>
    </header>
    
    <%= yield %>
    
    <footer>
      <p>© hogehoge</p>
    </footer>
  </body>
</html>